name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
jobs:
  unit_tests:
    runs-on: macos-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    #- name: Run for macOS
    #  run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test -project WeatherChallenge.xcodeproj -scheme "WeatherChallengeTests" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES | xcpretty
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test -project WeatherChallenge.xcodeproj -scheme "WeatheriOSTests" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.7,name=iPhone 12 PRO" ONLY_ACTIVE_ARCH=YES | xcpretty

